language: c
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq zlib1g-dev doxygen libfuse-dev libglobus-common-dev libglobus-gss-assist-dev libkrb5-dev libmysqlclient-dev libreadline-dev swig python-dev libperl5-dev m4
